name: ikus_app
description: IKUS OvGU App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.12.7+76

environment:
  flutter: '>=3.3.0'
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  file_picker: ^4.6.1 # Add this line for file picking
  permission_handler: ^10.0.0

  # core
  intl: 0.17.0 # used by table_calendar and for formatting dates
  dart_jsonwebtoken: 2.8.0 # jwt
  package_info: ^2.0.2 # show version and build of the app
  uuid: 3.0.7 # create device id
  html: ^0.15.0 # parse html
  collection: 1.17.0 # collection utilities
  crypto: 3.0.2 # hash registration tokens

  # i18n
  slang: 3.23.0
  slang_flutter: 3.23.0

  # storage
  hive: 2.2.3 # persistent storage
  hive_flutter: 1.1.0 # helper for hive
  flutter_secure_storage: 6.0.0 # for ovgu account

  # native utilities
  http: 0.13.6 # make http requests
  add_2_calendar: 2.2.4 # add calendar reminders
  map_launcher: 2.3.0+1 # launch external map app
  url_launcher: 6.1.11 # open links
  enough_mail: 2.1.1 # emails
  workmanager: 0.5.0 # run tasks in background
  flutter_local_notifications: 9.9.1 # show notifications
  audioplayers: 1.0.1 # play audio

  # components
  flutter_html: 3.0.0-beta.2 # show post content encoded in html
  flutter_map: 3.0.0 # show map location of events
  carousel_slider: 4.2.1 # slider (e.g. home page)
  table_calendar: 3.0.8 # calendar
  native_pdf_view: 6.0.0+1 # render handbook as pdf

dev_dependencies:
  hive_generator: 1.1.3
  build_runner: 2.3.3
  slang_build_runner: 3.23.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/img/maps/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
